#!/bin/bash

set -e

SIZES="
16,16x16
32,16x16@2x
32,32x32
64,32x32@2x
128,128x128
256,128x128@2x
256,256x256
512,256x256@2x
512,512x512
1024,512x512@2x
"

BASEDIR="$(mktemp -d)"
echo "Working in $BASEDIR..."

for SVG in "$*"
do
  echo "Processing $SVG file..."
  # take action on each file. $f store current file name
  BASE=$(basename "$SVG" | sed 's/\.[^\.]*$//')
  ICONSET="$BASE.iconset"
  DIR="$BASEDIR/icons/$ICONSET"
  mkdir -p "$DIR"
  for PARAMS in $SIZES; do
    SIZE=$(echo $PARAMS | cut -d, -f1)
    LABEL=$(echo $PARAMS | cut -d, -f2)
    svg2png -w $SIZE -h $SIZE "$SVG" "$DIR"/icon_$LABEL.png || true
  done

  iconutil -c icns "$DIR" || true
  rm -rf "$DIR"
  cp "$BASEDIR/icons/$BASE.icns" "$(dirname "$SVG")"
done

rm -rf "$BASEDIR"
